### ISSUE TITLE
Firefox 44.x removes Clipple from contextual menu

### ISSUE THREAD

**Issue by ChitlinsConCarne** [mooz/clipple#3]
I use Clipple ALL Day Every Day!!! Nothing else like it I can find - Clipboard-Plus is also not available in the context menu = Coincidence? Firefox 44.x+ defeating extended clipboards? PLEASE, Please, please fix this !!!

**Comment by mooz** [comment]
Solved in version `0.1.3`. 

Now the version is under the reviewing process. You can find it in https://addons.mozilla.org/en-US/firefox/addon/clipple/versions/
